version: "3"

services:
  app:
    build:
      context: .
    environment:
      - NODE_COMMAND=${NODE_COMMAND:-dev}
      - COMMIT_MSG=${COMMIT_MSG:-""}
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules